version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStart:
    # - location: scripts/reload-pm2.sh
    - location: scripts/load-docker-image.sh
      timeout: 300
      runas: root